### ISSUE TITLE
Cuberok 0.0.3 fails to build on Scientific Linux 5.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DrMoriarty/cuberok#1]
```
Trying to build an RPM package on Scientific Linux 5.2
(http://distrowatch.com/table.php?distribution=scientific). Build fails
(error messages are below).

To reproduce the problem one will have to
1. Download cuberok from offsite
(http://cuberok.googlecode.com/files/cuberok-0.0.3.tar.gz)
2. Untar it and replace libtaglib-devel with taglib-devel and libqt4-devel
with qt4-devel in cuberok.spec because appropriate packages are named
accordingly
3. Launch rpmbuild -ba cuberok.spec

Instead of successful build there is the following:

/usr/include/taglib/fileref.h:93: warning: 'class
TagLib::FileRef::FileTypeResolver' has virtual functions but non-virtual
destructor
src/ui_cuberok.h: In member function 'void
Ui_CuberokClass::setupUi(QMainWindow*)':
src/ui_cuberok.h:127: error: 'class QMainWindow' has no member named
'setDockOptions'
src/ui_cuberok.h:127: error: 'AllowNestedDocks' is not a member of
'QMainWindow'
src/ui_cuberok.h:127: error: 'AllowTabbedDocks' is not a member of
'QMainWindow'
src/ui_cuberok.h:127: error: 'AnimatedDocks' is not a member of 'QMainWindow'
src/ui_cuberok.h:127: error: 'ForceTabbedDocks' is not a member of
'QMainWindow'
src/ui_cuberok.h:127: error: 'VerticalTabs' is not a member of 'QMainWindow'
src/ui_cuberok.h:286: error: 'class QVBoxLayout' has no member named
'setContentsMargins'
src/ui_cuberok.h:314: error: 'class QHBoxLayout' has no member named
'setContentsMargins'
src/ui_cuberok.h:346: error: 'class QVBoxLayout' has no member named
'setContentsMargins'
src/ui_cuberok.h:359: error: 'class QHBoxLayout' has no member named
'setContentsMargins'
src/ui_cuberok.h:404: error: 'class QVBoxLayout' has no member named
'setContentsMargins'
src/ui_cuberok.h:411: error: 'class QTreeView' has no member named
'setAutoExpandDelay'
src/ui_cuberok.h:428: error: 'class QVBoxLayout' has no member named
'setContentsMargins'
src/ui_lookandfeel.h: In member function 'void
Ui_LookAndFeelClass::setupUi(QDialog*)':
src/ui_lookandfeel.h:279: error: 'class QHBoxLayout' has no member named
'setContentsMargins'
src/tagger.h: At global scope:
src/tagger.h:25: warning: '_autoCorrect' defined but not used
src/tagger.h:26: warning: '_saveCorrected' defined but not used
make: *** [unix/obj/cuberok.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.62212 (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.62212 (%build)


Don't know if that matters but I have no Audiere installed. GStreamer is
present and works OK. Also I'll report any extra info if required. Also
apologize my poor English (I'm a Russian native speaker)

```

Original issue reported on code.google.com by `iamde...@gmail.com` on 9 Sep 2008 at 11:14
